const jwtAndKey = [{ bearerAuth: [], apiKeyAuth: [], csrfToken: [] }];
const jwtAndKeyRead = [{ bearerAuth: [], apiKeyAuth: [] }];

export const projectPaths = {

  // ─────────────────────────────────────────────────────────────
  //  Collection routes
  // ─────────────────────────────────────────────────────────────
  '/projects': {
    get: {
      tags: ['Projects'],
      summary: 'List all projects — paginated, searchable, filterable',
      description: [
        '## Get All Projects',
        '',
        'Returns a paginated list of freelancer projects.',
        '',
        '**Auth required:** JWT Bearer token + API key header (`x-api-key`) + role permission `project_management:view`',
        '',
        '### Search',
        'Pass `search` to do a case-insensitive match across:',
        '`client_name`, `client_mobile`, `client_email`, `project_name`, `reference_id`',
        '',
        '### Filters',
        '| Param | Type | Description |',
        '|-------|------|-------------|',
        '| `project_status` | enum | Filter by project lifecycle stage |',
        '| `project_type` | enum | Filter by industry type (salon, gym, etc.) |',
        '| `payment_status` | enum | Filter by billing stage (pending/partial/paid/overdue) |',
        '| `is_lead_converted` | boolean | Filter converted vs unconverted leads |',
        '| `is_maintenance_mode` | boolean | Filter projects currently in maintenance |',
        '| `date_from` / `date_to` | date | Range filter on `createdAt` |',
        '| `is_active` | boolean | Default `true` (shows only active records) |',
        '',
        '### Pagination',
        'Pass `page` + `limit`. Omit both to get all records in one response.',
        '',
        '### Response',
        '```json',
        '{',
        '  "success": true,',
        '  "message": "Projects fetched successfully",',
        '  "data": {',
        '    "data": [ ...projects ],',
        '    "total": 42,',
        '    "page": 1,',
        '    "limit": 10,',
        '    "totalPages": 5',
        '  }',
        '}',
        '```',
      ].join('\n'),
      security: jwtAndKeyRead,
      parameters: [
        { in: 'query', name: 'page',                 schema: { type: 'integer', example: 1 },     description: 'Page number (default: 1)' },
        { in: 'query', name: 'limit',                schema: { type: 'integer', example: 10 },    description: 'Items per page (default: 10)' },
        { in: 'query', name: 'search',               schema: { type: 'string',  example: 'Rahul' }, description: 'Search across client_name, client_mobile, client_email, project_name, reference_id (case-insensitive)' },
        { in: 'query', name: 'project_status',       schema: { type: 'string',  enum: ['lead', 'in_progress', 'completed', 'on_hold', 'cancelled'] }, description: 'Filter by project lifecycle stage' },
        { in: 'query', name: 'project_type',         schema: { type: 'string',  enum: ['salon', 'gym', 'spa', 'legal', 'hospital', 'school_management', 'ecommerce', 'real_estate', 'restaurant', 'hotel', 'travel', 'finance', 'inventory', 'crm', 'erp', 'other'] }, description: 'Filter by industry / project category' },
        { in: 'query', name: 'payment_status',       schema: { type: 'string',  enum: ['pending', 'partial', 'paid', 'overdue'] }, description: 'Filter by billing/payment stage' },
        { in: 'query', name: 'is_lead_converted',    schema: { type: 'boolean', example: true },  description: 'true = show only converted leads | false = show unconverted leads' },
        { in: 'query', name: 'is_maintenance_mode',  schema: { type: 'boolean', example: false }, description: 'Filter projects currently in maintenance mode' },
        { in: 'query', name: 'date_from',            schema: { type: 'string',  format: 'date', example: '2026-01-01' }, description: 'Show records where createdAt >= date_from' },
        { in: 'query', name: 'date_to',              schema: { type: 'string',  format: 'date', example: '2026-12-31' }, description: 'Show records where createdAt <= date_to (end of day: 23:59:59)' },
        { in: 'query', name: 'is_active',            schema: { type: 'boolean', example: true },  description: 'Default true — pass false to include soft-deleted records' },
      ],
      responses: {
        200: { description: 'Paginated project list', content: { 'application/json': { schema: { $ref: '#/components/schemas/PaginatedProjectResponse' } } } },
        401: { description: 'Unauthorized — missing or expired JWT / invalid API key' },
        403: { description: 'Forbidden — role does not have project_management:view permission' },
      },
    },

    post: {
      tags: ['Projects'],
      summary: 'Create a new project with client info, billing & payment terms',
      description: [
        '## Create Project',
        '',
        'Creates a new freelancer project record and auto-generates a unique `reference_id` in the format `PRJ-DDMMYYYY-NNNNN` (e.g. `PRJ-14062026-00001`).',
        '',
        '**Auth required:** JWT Bearer + API key + CSRF token + role permission `project_management:create`',
        '',
        '### Client Information',
        '| Field | Required | Description |',
        '|-------|----------|-------------|',
        '| `client_name` | ✅ | Full name of the client |',
        '| `client_mobile` | ✅ | Primary mobile number |',
        '| `client_alternative_mobile` | ❌ | Secondary / WhatsApp number |',
        '| `client_email` | ❌ | Client Gmail / email address |',
        '',
        '### Project Details',
        '| Field | Required | Description |',
        '|-------|----------|-------------|',
        '| `project_name` | ✅ | Name of the project |',
        '| `project_type` | ✅ | Industry category — see enum values below |',
        '| `project_description` | ❌ | Detailed description of scope |',
        '| `project_status` | ❌ | Defaults to `lead` |',
        '| `is_lead_converted` | ❌ | Whether the lead became a confirmed project (default: false) |',
        '| `lead_converted_date` | ❌ | Date when lead was officially converted |',
        '',
        '### Deployment Info',
        '| Field | Required | Description |',
        '|-------|----------|-------------|',
        '| `project_github_link` | ❌ | GitHub repository URL |',
        '| `frontend_deploy_on` | ❌ | Platform where frontend is hosted (vercel, netlify, etc.) |',
        '| `frontend_deploy_url` | ❌ | Live frontend URL |',
        '| `backend_deploy_on` | ❌ | Platform where backend/API is hosted |',
        '| `backend_deploy_url` | ❌ | Live backend URL |',
        '',
        '### Maintenance',
        '| Field | Required | Description |',
        '|-------|----------|-------------|',
        '| `is_maintenance_mode` | ❌ | Toggle maintenance mode (default: false) |',
        '| `maintenance_start_date` | ❌ | ISO date when maintenance contract started |',
        '| `maintenance_end_date` | ❌ | ISO date when maintenance contract ends |',
        '',
        '### Billing & Payment Terms',
        '| Field | Required | Description |',
        '|-------|----------|-------------|',
        '| `payment_total_amount` | ✅ | Total project cost (e.g. 20000) |',
        '| `payment_terms` | ❌ | Array of installment records (see below) |',
        '',
        '**payment_terms example** — 20,000 split into 4 terms of 5,000:',
        '```json',
        '"payment_terms": [',
        '  { "term_number": 1, "amount": 5000, "due_date": "2026-07-01", "note": "Advance" },',
        '  { "term_number": 2, "amount": 5000, "due_date": "2026-08-01" },',
        '  { "term_number": 3, "amount": 5000, "due_date": "2026-09-01" },',
        '  { "term_number": 4, "amount": 5000, "due_date": "2026-10-01", "note": "Final delivery" }',
        ']',
        '```',
        '',
        '> **Auto-calculation:** `payment_paid_amount`, `payment_due_amount`, and `payment_status` are **automatically computed** from the payment_terms array. You do NOT need to send them.',
      ].join('\n'),
      security: jwtAndKey,
      requestBody: {
        required: true,
        content: { 'application/json': { schema: { $ref: '#/components/schemas/CreateProjectDto' } } },
      },
      responses: {
        201: { description: 'Project created successfully', content: { 'application/json': { schema: { $ref: '#/components/schemas/ProjectSuccessResponse' } } } },
        400: { description: 'Validation error — required fields missing or invalid enum values', content: { 'application/json': { schema: { $ref: '#/components/schemas/ApiError' } } } },
        401: { description: 'Unauthorized — missing or expired JWT / invalid API key' },
        403: { description: 'Forbidden — invalid CSRF token or missing create permission' },
      },
    },
  },

  // ─────────────────────────────────────────────────────────────
  //  Single-project routes
  // ─────────────────────────────────────────────────────────────
  '/projects/{id}': {
    get: {
      tags: ['Projects'],
      summary: 'Get a single project by MongoDB ID',
      description: [
        '## Get Project by ID',
        '',
        'Returns full project details including all payment terms.',
        '',
        '**Auth required:** JWT Bearer + API key + role permission `project_management:view`',
        '',
        '**Path param:** `id` — MongoDB ObjectId of the project document.',
        '',
        '### Response includes',
        '- Complete client info',
        '- Project status, type, description',
        '- Deployment details (github link, frontend/backend platform & URL)',
        '- Maintenance mode flag and dates',
        '- Full payment summary (`payment_total_amount`, `payment_paid_amount`, `payment_due_amount`, `payment_status`)',
        '- All payment terms with per-term paid/pending status',
      ].join('\n'),
      security: jwtAndKeyRead,
      parameters: [
        { in: 'path', name: 'id', required: true, schema: { type: 'string', example: '664f1a2b3c4d5e6f7a8b9c0d' }, description: 'MongoDB ObjectId of the project' },
      ],
      responses: {
        200: { description: 'Project details', content: { 'application/json': { schema: { $ref: '#/components/schemas/ProjectSuccessResponse' } } } },
        401: { description: 'Unauthorized' },
        403: { description: 'Forbidden — missing view permission' },
        404: { description: 'Project not found' },
      },
    },

    patch: {
      tags: ['Projects'],
      summary: 'Update project details, billing or payment terms',
      description: [
        '## Update Project',
        '',
        'Partially updates any project field. Send only the fields you want to change — all fields are optional.',
        '',
        '**Auth required:** JWT Bearer + API key + CSRF token + role permission `project_management:edit`',
        '',
        '### Updating Payment Terms',
        'When you send `payment_terms`, the array **replaces** the existing terms. Each object must include `term_number` (used to match the existing term) plus any fields you want to update.',
        '',
        '**Example — mark term 2 as paid and update due dates:**',
        '```json',
        '{',
        '  "payment_terms": [',
        '    { "term_number": 1, "amount": 5000, "due_date": "2026-07-01" },',
        '    { "term_number": 2, "amount": 5000, "status": "paid", "paid_date": "2026-07-15", "payment_mode": "upi" },',
        '    { "term_number": 3, "amount": 5000, "due_date": "2026-09-01" },',
        '    { "term_number": 4, "amount": 5000, "due_date": "2026-10-01" }',
        '  ]',
        '}',
        '```',
        '',
        '> **Auto-calculation:** After any payment_terms update, `payment_paid_amount`, `payment_due_amount`, and `payment_status` are recalculated automatically.',
        '',
        '### Updating Project Status',
        '```json',
        '{ "project_status": "in_progress", "is_lead_converted": true, "lead_converted_date": "2026-06-14T10:00:00Z" }',
        '```',
        '',
        '### Enabling Maintenance Mode',
        '```json',
        '{ "is_maintenance_mode": true, "maintenance_start_date": "2026-07-01", "maintenance_end_date": "2026-12-31" }',
        '```',
        '',
        '### Soft-deleting (deactivate without hard delete)',
        '```json',
        '{ "is_active": false }',
        '```',
      ].join('\n'),
      security: jwtAndKey,
      parameters: [
        { in: 'path', name: 'id', required: true, schema: { type: 'string', example: '664f1a2b3c4d5e6f7a8b9c0d' }, description: 'MongoDB ObjectId of the project' },
      ],
      requestBody: {
        required: true,
        content: { 'application/json': { schema: { $ref: '#/components/schemas/UpdateProjectDto' } } },
      },
      responses: {
        200: { description: 'Project updated successfully', content: { 'application/json': { schema: { $ref: '#/components/schemas/ProjectSuccessResponse' } } } },
        400: { description: 'Validation error or empty body' },
        401: { description: 'Unauthorized' },
        403: { description: 'Forbidden — invalid CSRF token or missing edit permission' },
        404: { description: 'Project not found' },
      },
    },

    delete: {
      tags: ['Projects'],
      summary: 'Hard-delete a project (permanent)',
      description: [
        '## Delete Project',
        '',
        '**Permanently removes** the project document from MongoDB. This action is irreversible.',
        '',
        '**Auth required:** JWT Bearer + API key + CSRF token + role permission `project_management:delete`',
        '',
        '> **Tip:** To deactivate without deleting, use PATCH with `{ "is_active": false }` instead.',
      ].join('\n'),
      security: jwtAndKey,
      parameters: [
        { in: 'path', name: 'id', required: true, schema: { type: 'string', example: '664f1a2b3c4d5e6f7a8b9c0d' }, description: 'MongoDB ObjectId of the project' },
      ],
      responses: {
        200: { description: 'Project deleted successfully' },
        401: { description: 'Unauthorized' },
        403: { description: 'Forbidden — invalid CSRF token or missing delete permission' },
        404: { description: 'Project not found' },
      },
    },
  },

  // ─────────────────────────────────────────────────────────────
  //  Payment term sub-routes
  // ─────────────────────────────────────────────────────────────
  '/projects/{id}/payment-terms': {
    post: {
      tags: ['Projects — Payment Terms'],
      summary: 'Add a new payment term to an existing project',
      description: [
        '## Add Payment Term',
        '',
        'Appends a single new installment record to the project\'s `payment_terms` array.',
        '',
        '**Auth required:** JWT Bearer + API key + CSRF token + role permission `project_management:edit`',
        '',
        '### When to use this vs PATCH /projects/:id',
        '- **This endpoint** → add one new term without sending all existing terms again.',
        '- **PATCH /projects/:id** → replace / update the full payment_terms array in one shot.',
        '',
        '### Term number uniqueness',
        'Each `term_number` must be unique within the project. Sending a duplicate returns **409 Conflict**.',
        '',
        '### Example',
        '```json',
        '{',
        '  "term_number": 5,',
        '  "amount": 3000,',
        '  "due_date": "2026-11-01",',
        '  "payment_mode": "bank_transfer",',
        '  "note": "Extra feature addition"',
        '}',
        '```',
        '',
        '> After adding, `payment_due_amount` is recalculated automatically. New terms always start with `status: "pending"`.',
      ].join('\n'),
      security: jwtAndKey,
      parameters: [
        { in: 'path', name: 'id', required: true, schema: { type: 'string', example: '664f1a2b3c4d5e6f7a8b9c0d' }, description: 'MongoDB ObjectId of the project' },
      ],
      requestBody: {
        required: true,
        content: {
          'application/json': {
            schema: { $ref: '#/components/schemas/AddPaymentTermDto' },
          },
        },
      },
      responses: {
        200: { description: 'Payment term added and payment summary recalculated', content: { 'application/json': { schema: { $ref: '#/components/schemas/ProjectSuccessResponse' } } } },
        400: { description: 'term_number or amount missing' },
        401: { description: 'Unauthorized' },
        403: { description: 'Forbidden — invalid CSRF token or missing edit permission' },
        404: { description: 'Project not found' },
        409: { description: 'Conflict — term_number already exists in this project' },
      },
    },
  },

  '/projects/{id}/payment-terms/{term_number}/pay': {
    patch: {
      tags: ['Projects — Payment Terms'],
      summary: 'Mark a specific payment term as paid',
      description: [
        '## Mark Term as Paid',
        '',
        'Marks a single payment installment as `paid` and updates the project\'s payment summary.',
        '',
        '**Auth required:** JWT Bearer + API key + CSRF token + role permission `project_management:edit`',
        '',
        '### What happens internally',
        '1. Finds the term by `term_number`',
        '2. Sets `status → "paid"` and records `paid_date` (defaults to now if not provided)',
        '3. Recalculates `payment_paid_amount`, `payment_due_amount`, and `payment_status`:',
        '   - All terms paid → `payment_status = "paid"`',
        '   - Some terms paid → `payment_status = "partial"`',
        '   - No terms paid → `payment_status = "pending"`',
        '',
        '### Example',
        'Client pays term 2 via UPI on 15 July 2026:',
        '```json',
        '{',
        '  "paid_date": "2026-07-15T11:30:00Z",',
        '  "payment_mode": "upi"',
        '}',
        '```',
        '',
        '> Both `paid_date` and `payment_mode` are optional — `paid_date` defaults to current timestamp.',
      ].join('\n'),
      security: jwtAndKey,
      parameters: [
        { in: 'path', name: 'id',          required: true, schema: { type: 'string',  example: '664f1a2b3c4d5e6f7a8b9c0d' }, description: 'MongoDB ObjectId of the project' },
        { in: 'path', name: 'term_number', required: true, schema: { type: 'integer', example: 2 },                           description: 'The term_number to mark as paid' },
      ],
      requestBody: {
        required: false,
        content: {
          'application/json': {
            schema: { $ref: '#/components/schemas/MarkTermPaidDto' },
          },
        },
      },
      responses: {
        200: { description: 'Term marked as paid — payment summary updated', content: { 'application/json': { schema: { $ref: '#/components/schemas/ProjectSuccessResponse' } } } },
        400: { description: 'Invalid term_number (not a number)' },
        401: { description: 'Unauthorized' },
        403: { description: 'Forbidden — invalid CSRF token or missing edit permission' },
        404: { description: 'Project not found or term_number does not exist' },
      },
    },
  },

  // ─────────────────────────────────────────────────────────────
  //  Maintenance term sub-routes
  // ─────────────────────────────────────────────────────────────
  '/projects/{id}/maintenance-terms': {
    post: {
      tags: ['Projects — Maintenance Terms'],
      summary: 'Add a new maintenance billing term to a project',
      description: [
        '## Add Maintenance Term',
        '',
        'Appends a single new maintenance installment record to the project\'s `maintenance_terms` array.',
        '',
        '**Auth required:** JWT Bearer + API key + CSRF token + role permission `project_management:edit`',
        '',
        '### Fields',
        '| Field | Required | Description |',
        '|-------|----------|-------------|',
        '| `term_number` | ✅ | Unique number within maintenance_terms |',
        '| `amount` | ✅ | Billing amount for this maintenance period |',
        '| `start_date` | ❌ | Start of maintenance coverage for this term |',
        '| `end_date` | ❌ | End of maintenance coverage for this term |',
        '| `due_date` | ❌ | Payment due date |',
        '| `payment_mode` | ❌ | cash / upi / bank_transfer / cheque / online |',
        '| `note` | ❌ | Free-text note |',
        '',
        '### Example — quarterly maintenance billing',
        '```json',
        '{',
        '  "term_number": 1,',
        '  "amount": 2000,',
        '  "start_date": "2026-07-01T00:00:00Z",',
        '  "end_date": "2026-09-30T23:59:59Z",',
        '  "due_date": "2026-07-05T00:00:00Z",',
        '  "note": "Q3 maintenance"',
        '}',
        '```',
        '',
        '> New terms always start with `status: "pending"`. After adding, `maintenance_due_amount` is recalculated automatically.',
      ].join('\n'),
      security: jwtAndKey,
      parameters: [
        { in: 'path', name: 'id', required: true, schema: { type: 'string', example: '664f1a2b3c4d5e6f7a8b9c0d' }, description: 'MongoDB ObjectId of the project' },
      ],
      requestBody: {
        required: true,
        content: {
          'application/json': { schema: { $ref: '#/components/schemas/AddMaintenanceTermDto' } },
        },
      },
      responses: {
        200: { description: 'Maintenance term added and summary recalculated', content: { 'application/json': { schema: { $ref: '#/components/schemas/ProjectSuccessResponse' } } } },
        400: { description: 'term_number or amount missing' },
        401: { description: 'Unauthorized' },
        403: { description: 'Forbidden — invalid CSRF token or missing edit permission' },
        404: { description: 'Project not found' },
        409: { description: 'Conflict — maintenance term_number already exists in this project' },
      },
    },
  },

  '/projects/{id}/maintenance-terms/{term_number}/pay': {
    patch: {
      tags: ['Projects — Maintenance Terms'],
      summary: 'Mark a maintenance term as paid',
      description: [
        '## Mark Maintenance Term as Paid',
        '',
        'Marks a single maintenance installment as `paid` and updates `maintenance_paid_amount`, `maintenance_due_amount`, and `maintenance_payment_status`.',
        '',
        '**Auth required:** JWT Bearer + API key + CSRF token + role permission `project_management:edit`',
        '',
        '### What happens internally',
        '1. Finds the maintenance term by `term_number`',
        '2. Sets `status → "paid"`, records `paid_date` (defaults to now) and `payment_mode`',
        '3. Recalculates the maintenance payment summary:',
        '   - All terms paid → `maintenance_payment_status = "paid"`',
        '   - Some terms paid → `maintenance_payment_status = "partial"`',
        '   - No terms paid → `maintenance_payment_status = "pending"`',
        '',
        '### Example',
        '```json',
        '{',
        '  "paid_date": "2026-07-10T09:00:00Z",',
        '  "payment_mode": "bank_transfer"',
        '}',
        '```',
        '',
        '> Both fields are optional — `paid_date` defaults to the current server timestamp.',
      ].join('\n'),
      security: jwtAndKey,
      parameters: [
        { in: 'path', name: 'id',          required: true, schema: { type: 'string',  example: '664f1a2b3c4d5e6f7a8b9c0d' }, description: 'MongoDB ObjectId of the project' },
        { in: 'path', name: 'term_number', required: true, schema: { type: 'integer', example: 1 },                           description: 'Maintenance term_number to mark as paid' },
      ],
      requestBody: {
        required: false,
        content: {
          'application/json': { schema: { $ref: '#/components/schemas/MarkTermPaidDto' } },
        },
      },
      responses: {
        200: { description: 'Maintenance term marked as paid — summary updated', content: { 'application/json': { schema: { $ref: '#/components/schemas/ProjectSuccessResponse' } } } },
        400: { description: 'Invalid term_number (not a number)' },
        401: { description: 'Unauthorized' },
        403: { description: 'Forbidden — invalid CSRF token or missing edit permission' },
        404: { description: 'Project not found or maintenance term_number does not exist' },
      },
    },
  },
};

// ─────────────────────────────────────────────────────────────────────────────
//  Schema definitions
// ─────────────────────────────────────────────────────────────────────────────
export const projectSchemas = {

  PaymentTerm: {
    type: 'object',
    description: 'A single payment installment within a project',
    properties: {
      term_number:  { type: 'integer', example: 1,               description: 'Installment number (must be unique within the project)' },
      amount:       { type: 'number',  example: 5000,            description: 'Amount for this installment in INR (or base currency)' },
      due_date:     { type: 'string',  format: 'date-time',      description: 'Expected payment date (ISO 8601)' },
      paid_date:    { type: 'string',  format: 'date-time',      description: 'Actual date payment was received' },
      payment_mode: { type: 'string',  enum: ['cash', 'bank_transfer', 'upi', 'cheque', 'online'], description: 'Mode of payment' },
      status:       { type: 'string',  enum: ['pending', 'paid', 'overdue'], example: 'pending', description: 'Current status of this installment' },
      note:         { type: 'string',  example: 'Advance payment', description: 'Optional note or label for this term' },
    },
  },

  MaintenanceTerm: {
    type: 'object',
    description: 'A single maintenance billing installment — covers a specific maintenance period',
    properties: {
      term_number:  { type: 'integer', example: 1,                          description: 'Term number (must be unique within maintenance_terms)' },
      amount:       { type: 'number',  example: 2000,                       description: 'Billing amount for this maintenance period' },
      start_date:   { type: 'string',  format: 'date-time',                 description: 'Start of maintenance coverage for this term' },
      end_date:     { type: 'string',  format: 'date-time',                 description: 'End of maintenance coverage for this term' },
      due_date:     { type: 'string',  format: 'date-time',                 description: 'Payment due date for this maintenance term' },
      paid_date:    { type: 'string',  format: 'date-time',                 description: 'Actual payment received date' },
      payment_mode: { type: 'string',  enum: ['cash', 'bank_transfer', 'upi', 'cheque', 'online'], description: 'Payment method used' },
      status:       { type: 'string',  enum: ['pending', 'paid', 'overdue'], example: 'pending', description: 'Payment status for this maintenance term' },
      note:         { type: 'string',  example: 'Q3 maintenance',           description: 'Optional note for this term (e.g. quarter label)' },
    },
  },

  Project: {
    type: 'object',
    description: 'Full project document returned by the API',
    properties: {
      _id:           { type: 'string', example: '664f1a2b3c4d5e6f7a8b9c0d', description: 'MongoDB ObjectId' },
      reference_id:  { type: 'string', example: 'PRJ-14062026-00001',       description: 'Auto-generated human-readable ID (PRJ-DDMMYYYY-NNNNN)' },

      client_name:                { type: 'string',  example: 'Rahul Sharma',       description: 'Full name of the client' },
      client_mobile:              { type: 'string',  example: '9876543210',         description: 'Primary contact number' },
      client_alternative_mobile:  { type: 'string',  example: '9123456780',         description: 'Secondary / WhatsApp number (optional)' },
      client_email:               { type: 'string',  example: 'rahul@gmail.com',    description: 'Client email / Gmail address (optional)' },

      project_name:         { type: 'string', example: 'Salon CRM Software',    description: 'Name of the project' },
      project_type:         { type: 'string', enum: ['salon', 'gym', 'spa', 'legal', 'hospital', 'school_management', 'ecommerce', 'real_estate', 'restaurant', 'hotel', 'travel', 'finance', 'inventory', 'crm', 'erp', 'other'], description: 'Industry category of the project' },
      project_description:  { type: 'string', example: 'Appointment booking + billing system for a salon chain', description: 'Detailed project scope description' },
      project_status:       { type: 'string', enum: ['lead', 'in_progress', 'completed', 'on_hold', 'cancelled'], example: 'in_progress', description: 'Current lifecycle stage of the project' },

      is_lead_converted:   { type: 'boolean', example: true,                      description: 'Whether the initial lead was converted to a paid project' },
      lead_converted_date: { type: 'string',  format: 'date-time',                description: 'Date the lead was officially converted' },

      project_github_link:  { type: 'string', example: 'https://github.com/org/salon-crm', description: 'GitHub repository URL' },
      frontend_deploy_on:   { type: 'string', enum: ['vercel', 'netlify', 'aws', 'digital_ocean', 'hostinger', 'cpanel', 'vps', 'heroku', 'render', 'firebase', 'other', 'na'], example: 'vercel',    description: 'Platform hosting the frontend' },
      frontend_deploy_url:  { type: 'string', example: 'https://salon-crm.vercel.app',     description: 'Live frontend URL' },
      backend_deploy_on:    { type: 'string', enum: ['vercel', 'netlify', 'aws', 'digital_ocean', 'hostinger', 'cpanel', 'vps', 'heroku', 'render', 'firebase', 'other', 'na'], example: 'hostinger', description: 'Platform hosting the backend / API' },
      backend_deploy_url:   { type: 'string', example: 'https://api.salon-crm.in',         description: 'Live backend / API URL' },

      is_maintenance_mode:    { type: 'boolean', example: false,          description: 'Whether the project is currently in active maintenance contract' },
      maintenance_start_date: { type: 'string',  format: 'date-time',    description: 'Maintenance contract start date' },
      maintenance_end_date:   { type: 'string',  format: 'date-time',    description: 'Maintenance contract end / expiry date' },

      payment_status:       { type: 'string',  enum: ['pending', 'partial', 'paid', 'overdue'], example: 'partial', description: 'Overall billing status — auto-calculated from payment_terms' },
      payment_total_amount: { type: 'number',  example: 20000,   description: 'Total agreed project cost' },
      payment_paid_amount:  { type: 'number',  example: 5000,    description: 'Sum of all paid installments (auto-calculated)' },
      payment_due_amount:   { type: 'number',  example: 15000,   description: 'Remaining amount to be collected (auto-calculated)' },
      payment_terms: {
        type: 'array',
        description: 'Project installment schedule — each term tracks amount, due date, paid date, mode and status',
        items: { $ref: '#/components/schemas/PaymentTerm' },
      },

      maintenance_payment_status:  { type: 'string',  enum: ['pending', 'partial', 'paid', 'overdue'], example: 'pending', description: 'Maintenance billing status — auto-calculated from maintenance_terms' },
      maintenance_total_amount:    { type: 'number',  example: 8000,  description: 'Total maintenance contract amount' },
      maintenance_paid_amount:     { type: 'number',  example: 0,     description: 'Sum of paid maintenance installments (auto-calculated)' },
      maintenance_due_amount:      { type: 'number',  example: 8000,  description: 'Remaining maintenance amount due (auto-calculated)' },
      maintenance_terms: {
        type: 'array',
        description: 'Maintenance billing schedule — each term has a coverage period (start_date → end_date) plus payment tracking',
        items: { $ref: '#/components/schemas/MaintenanceTerm' },
      },

      created_by: { type: 'string', example: '664f1a2b3c4d5e6f7a8b9c0d', description: 'user_id from JWT of the person who created this record' },
      is_active:  { type: 'boolean', example: true, description: 'Soft-delete flag — false = deactivated/archived' },
      createdAt:  { type: 'string',  format: 'date-time' },
      updatedAt:  { type: 'string',  format: 'date-time' },
    },
  },

  CreateProjectDto: {
    type: 'object',
    required: ['client_name', 'client_mobile', 'project_name', 'project_type', 'payment_total_amount'],
    description: 'Request body for creating a new project',
    properties: {
      client_name:                { type: 'string',  example: 'Rahul Sharma',      description: '(required) Full name of the client' },
      client_mobile:              { type: 'string',  example: '9876543210',        description: '(required) Primary mobile number' },
      client_alternative_mobile:  { type: 'string',  example: '9123456780',        description: 'Secondary contact number (optional)' },
      client_email:               { type: 'string',  example: 'rahul@gmail.com',   description: 'Client Gmail or email (optional)' },
      project_name:               { type: 'string',  example: 'Salon CRM Software', description: '(required) Project title' },
      project_type: {
        type: 'string',
        enum: ['salon', 'gym', 'spa', 'legal', 'hospital', 'school_management', 'ecommerce', 'real_estate', 'restaurant', 'hotel', 'travel', 'finance', 'inventory', 'crm', 'erp', 'other'],
        example: 'salon',
        description: '(required) Industry category',
      },
      project_description:   { type: 'string',  example: 'Booking + billing system',        description: 'Detailed scope description' },
      project_status:        { type: 'string',  enum: ['lead', 'in_progress', 'completed', 'on_hold', 'cancelled'], example: 'lead', description: 'Defaults to "lead" if not provided' },
      is_lead_converted:     { type: 'boolean', example: false,                              description: 'Defaults to false' },
      lead_converted_date:   { type: 'string',  format: 'date-time',                         description: 'ISO 8601 date when lead converted' },
      project_github_link:   { type: 'string',  example: 'https://github.com/org/repo',      description: 'GitHub repository URL' },
      frontend_deploy_on:    { type: 'string',  enum: ['vercel', 'netlify', 'aws', 'digital_ocean', 'hostinger', 'cpanel', 'vps', 'heroku', 'render', 'firebase', 'other', 'na'], example: 'vercel' },
      frontend_deploy_url:   { type: 'string',  example: 'https://myproject.vercel.app' },
      backend_deploy_on:     { type: 'string',  enum: ['vercel', 'netlify', 'aws', 'digital_ocean', 'hostinger', 'cpanel', 'vps', 'heroku', 'render', 'firebase', 'other', 'na'], example: 'hostinger' },
      backend_deploy_url:    { type: 'string',  example: 'https://api.myproject.in' },
      is_maintenance_mode:   { type: 'boolean', example: false },
      maintenance_start_date:{ type: 'string',  format: 'date-time' },
      maintenance_end_date:  { type: 'string',  format: 'date-time' },
      payment_total_amount:  { type: 'number',  example: 20000,                              description: '(required) Total agreed project cost' },
      payment_terms: {
        type: 'array',
        description: 'Optional installment schedule — each term must have a unique term_number',
        items: {
          type: 'object',
          required: ['term_number', 'amount'],
          properties: {
            term_number:  { type: 'integer', example: 1 },
            amount:       { type: 'number',  example: 5000 },
            due_date:     { type: 'string',  format: 'date-time', example: '2026-07-01T00:00:00Z' },
            payment_mode: { type: 'string',  enum: ['cash', 'bank_transfer', 'upi', 'cheque', 'online'] },
            note:         { type: 'string',  example: 'Advance' },
          },
        },
        example: [
          { term_number: 1, amount: 5000, due_date: '2026-07-01T00:00:00Z', note: 'Advance' },
          { term_number: 2, amount: 5000, due_date: '2026-08-01T00:00:00Z' },
          { term_number: 3, amount: 5000, due_date: '2026-09-01T00:00:00Z' },
          { term_number: 4, amount: 5000, due_date: '2026-10-01T00:00:00Z', note: 'Final delivery' },
        ],
      },
      maintenance_total_amount: { type: 'number', example: 8000, description: 'Total maintenance contract amount (defaults to 0 if not provided)' },
      maintenance_terms: {
        type: 'array',
        description: 'Optional maintenance billing schedule — each term must have a unique term_number',
        items: {
          type: 'object',
          required: ['term_number', 'amount'],
          properties: {
            term_number:  { type: 'integer', example: 1 },
            amount:       { type: 'number',  example: 2000 },
            start_date:   { type: 'string',  format: 'date-time', example: '2026-07-01T00:00:00Z', description: 'Maintenance period start for this term' },
            end_date:     { type: 'string',  format: 'date-time', example: '2026-09-30T23:59:59Z', description: 'Maintenance period end for this term' },
            due_date:     { type: 'string',  format: 'date-time', example: '2026-07-05T00:00:00Z' },
            payment_mode: { type: 'string',  enum: ['cash', 'bank_transfer', 'upi', 'cheque', 'online'] },
            note:         { type: 'string',  example: 'Q3 maintenance' },
          },
        },
        example: [
          { term_number: 1, amount: 2000, start_date: '2026-07-01T00:00:00Z', end_date: '2026-09-30T23:59:59Z', due_date: '2026-07-05T00:00:00Z', note: 'Q3' },
          { term_number: 2, amount: 2000, start_date: '2026-10-01T00:00:00Z', end_date: '2026-12-31T23:59:59Z', due_date: '2026-10-05T00:00:00Z', note: 'Q4' },
        ],
      },
    },
  },

  UpdateProjectDto: {
    type: 'object',
    minProperties: 1,
    description: 'Request body for updating a project — all fields optional, send only what you want to change',
    properties: {
      client_name:                { type: 'string',  description: 'Update client full name' },
      client_mobile:              { type: 'string',  description: 'Update primary mobile number' },
      client_alternative_mobile:  { type: 'string',  description: 'Update alternative mobile number' },
      client_email:               { type: 'string',  description: 'Update client email' },
      project_name:               { type: 'string',  description: 'Update project title' },
      project_type:               { type: 'string',  enum: ['salon', 'gym', 'spa', 'legal', 'hospital', 'school_management', 'ecommerce', 'real_estate', 'restaurant', 'hotel', 'travel', 'finance', 'inventory', 'crm', 'erp', 'other'] },
      project_description:        { type: 'string' },
      project_status:             { type: 'string',  enum: ['lead', 'in_progress', 'completed', 'on_hold', 'cancelled'] },
      is_lead_converted:          { type: 'boolean', example: true },
      lead_converted_date:        { type: 'string',  format: 'date-time' },
      project_github_link:        { type: 'string' },
      frontend_deploy_on:         { type: 'string',  enum: ['vercel', 'netlify', 'aws', 'digital_ocean', 'hostinger', 'cpanel', 'vps', 'heroku', 'render', 'firebase', 'other', 'na'] },
      frontend_deploy_url:        { type: 'string' },
      backend_deploy_on:          { type: 'string',  enum: ['vercel', 'netlify', 'aws', 'digital_ocean', 'hostinger', 'cpanel', 'vps', 'heroku', 'render', 'firebase', 'other', 'na'] },
      backend_deploy_url:         { type: 'string' },
      is_maintenance_mode:        { type: 'boolean' },
      maintenance_start_date:     { type: 'string',  format: 'date-time' },
      maintenance_end_date:       { type: 'string',  format: 'date-time' },
      payment_total_amount:       { type: 'number',  example: 25000, description: 'Update total project cost (triggers payment recalculation)' },
      payment_status:             { type: 'string',  enum: ['pending', 'partial', 'paid', 'overdue'], description: 'Manually override payment_status (normally auto-calculated)' },
      payment_terms: {
        type: 'array',
        description: 'Replace full payment_terms array — use term_number to match existing entries',
        items: {
          type: 'object',
          required: ['term_number'],
          properties: {
            term_number:  { type: 'integer', example: 2,         description: 'Identifies which term to update' },
            amount:       { type: 'number',  example: 5000 },
            due_date:     { type: 'string',  format: 'date-time' },
            paid_date:    { type: 'string',  format: 'date-time' },
            payment_mode: { type: 'string',  enum: ['cash', 'bank_transfer', 'upi', 'cheque', 'online'] },
            status:       { type: 'string',  enum: ['pending', 'paid', 'overdue'] },
            note:         { type: 'string' },
          },
        },
      },
      maintenance_total_amount:   { type: 'number',  example: 10000, description: 'Update total maintenance contract amount (triggers maintenance recalculation)' },
      maintenance_payment_status: { type: 'string',  enum: ['pending', 'partial', 'paid', 'overdue'], description: 'Manually override maintenance_payment_status' },
      maintenance_terms: {
        type: 'array',
        description: 'Replace full maintenance_terms array — use term_number to match existing entries',
        items: {
          type: 'object',
          required: ['term_number'],
          properties: {
            term_number:  { type: 'integer', example: 1,         description: 'Identifies which maintenance term to update' },
            amount:       { type: 'number',  example: 2000 },
            start_date:   { type: 'string',  format: 'date-time' },
            end_date:     { type: 'string',  format: 'date-time' },
            due_date:     { type: 'string',  format: 'date-time' },
            paid_date:    { type: 'string',  format: 'date-time' },
            payment_mode: { type: 'string',  enum: ['cash', 'bank_transfer', 'upi', 'cheque', 'online'] },
            status:       { type: 'string',  enum: ['pending', 'paid', 'overdue'] },
            note:         { type: 'string' },
          },
        },
      },
      is_active: { type: 'boolean', example: false, description: 'Set false to soft-delete / archive the project' },
    },
  },

  AddMaintenanceTermDto: {
    type: 'object',
    required: ['term_number', 'amount'],
    description: 'Request body to add a single new maintenance billing term to a project',
    properties: {
      term_number:  { type: 'integer', example: 1,                          description: '(required) Must be unique within maintenance_terms' },
      amount:       { type: 'number',  example: 2000,                       description: '(required) Billing amount for this maintenance period' },
      start_date:   { type: 'string',  format: 'date-time', example: '2026-07-01T00:00:00Z', description: 'Start of maintenance coverage for this term' },
      end_date:     { type: 'string',  format: 'date-time', example: '2026-09-30T23:59:59Z', description: 'End of maintenance coverage for this term' },
      due_date:     { type: 'string',  format: 'date-time', example: '2026-07-05T00:00:00Z', description: 'Payment due date for this term' },
      payment_mode: { type: 'string',  enum: ['cash', 'bank_transfer', 'upi', 'cheque', 'online'] },
      note:         { type: 'string',  example: 'Q3 maintenance', description: 'Optional label or note' },
    },
  },

  AddPaymentTermDto: {
    type: 'object',
    required: ['term_number', 'amount'],
    description: 'Request body to add a single new installment term to a project',
    properties: {
      term_number:  { type: 'integer', example: 5,           description: '(required) Must be unique within the project' },
      amount:       { type: 'number',  example: 3000,        description: '(required) Amount for this installment' },
      due_date:     { type: 'string',  format: 'date-time',  description: 'Expected payment date (ISO 8601)' },
      payment_mode: { type: 'string',  enum: ['cash', 'bank_transfer', 'upi', 'cheque', 'online'] },
      note:         { type: 'string',  example: 'Extra feature addition' },
    },
  },

  MarkTermPaidDto: {
    type: 'object',
    description: 'Optional body when marking a term as paid',
    properties: {
      paid_date:    { type: 'string', format: 'date-time', example: '2026-07-15T11:30:00Z', description: 'Actual payment received date (defaults to current timestamp if not provided)' },
      payment_mode: { type: 'string', enum: ['cash', 'bank_transfer', 'upi', 'cheque', 'online'], example: 'upi', description: 'Payment method used' },
    },
  },

  ProjectSuccessResponse: {
    type: 'object',
    description: 'Standard success response wrapping a single project document',
    properties: {
      success: { type: 'boolean', example: true },
      message: { type: 'string',  example: 'Project created successfully' },
      data:    { $ref: '#/components/schemas/Project' },
    },
  },

  PaginatedProjectResponse: {
    type: 'object',
    description: 'Paginated response for project list endpoint',
    properties: {
      success: { type: 'boolean', example: true },
      message: { type: 'string',  example: 'Projects fetched successfully' },
      data: {
        type: 'object',
        properties: {
          data:       { type: 'array', items: { $ref: '#/components/schemas/Project' } },
          total:      { type: 'integer', example: 42,  description: 'Total records matching the filter' },
          page:       { type: 'integer', example: 1 },
          limit:      { type: 'integer', example: 10 },
          totalPages: { type: 'integer', example: 5 },
        },
      },
    },
  },
};
